// ---------------------------------------------------------------------------
// test_imzml.cpp
// Integration test for the imzML parser.
//
// Tests:
//   1. Load a 3x3 continuous imzML file (32-bit float, no compression)
//   2. Verify spectrum count, pixel coordinates, imaging mode
//   3. Validate binary array bounds
//   4. Read m/z and intensity data for each spectrum
//   5. Cross-validate peak 0 values against expected reference values
//
// The test data file is generated by gen_example_data.cpp (also in tests/).
//
// Usage:
//   ./test_imzml  [path/to/Example_Continuous.imzML]
//
// Without arguments the test looks in the same directory as the binary for
//   data/Example_Continuous.imzML  /  data/Example_Continuous.ibd
// ---------------------------------------------------------------------------
#include "imzml/ImzMLFile.h"
#include "imzml/ImzMLTypes.h"
#include "imzml/ImzMLWriter.h"

#include <iostream>
#include <iomanip>
#include <cmath>
#include <stdexcept>
#include <sstream>
#include <cassert>
#include <string>
#include <filesystem>
#include <numeric>
#include <algorithm>
#include <set>

// ---------------------------------------------------------------------------
// ANSI terminal helpers for clean test output
// ---------------------------------------------------------------------------
namespace term
{
    constexpr const char* RESET  = "\033[0m";
    constexpr const char* GREEN  = "\033[32m";
    constexpr const char* RED    = "\033[31m";
    constexpr const char* BOLD   = "\033[1m";
    constexpr const char* DIM    = "\033[2m";
}

// ---------------------------------------------------------------------------
// Test infrastructure
// ---------------------------------------------------------------------------
struct TestResult
{
    int passed{0};
    int failed{0};
};

static TestResult g_results;

#define EXPECT_EQ(actual, expected, msg)                                        \
    do {                                                                        \
        if ((actual) == (expected)) {                                           \
            std::cout << term::GREEN << "  [PASS]" << term::RESET              \
                      << "  " << (msg) << "\n";                                \
            ++g_results.passed;                                                 \
        } else {                                                                \
            std::cout << term::RED << "  [FAIL]" << term::RESET                \
                      << "  " << (msg) << "\n"                                 \
                      << "         expected: " << (expected)                   \
                      << "  got: " << (actual) << "\n";                        \
            ++g_results.failed;                                                 \
        }                                                                       \
    } while(0)

#define EXPECT_NEAR(actual, expected, tol, msg)                                 \
    do {                                                                        \
        double diff = std::abs(static_cast<double>(actual) -                   \
                               static_cast<double>(expected));                  \
        if (diff <= (tol)) {                                                    \
            std::cout << term::GREEN << "  [PASS]" << term::RESET              \
                      << "  " << (msg) << "\n";                                \
            ++g_results.passed;                                                 \
        } else {                                                                \
            std::cout << term::RED << "  [FAIL]" << term::RESET                \
                      << "  " << (msg) << "\n"                                 \
                      << "         expected: " << (expected)                   \
                      << "  got: " << (actual)                                 \
                      << "  diff: " << diff << "\n";                           \
            ++g_results.failed;                                                 \
        }                                                                       \
    } while(0)

#define EXPECT_TRUE(cond, msg)                                                  \
    do {                                                                        \
        if (cond) {                                                             \
            std::cout << term::GREEN << "  [PASS]" << term::RESET              \
                      << "  " << (msg) << "\n";                                \
            ++g_results.passed;                                                 \
        } else {                                                                \
            std::cout << term::RED << "  [FAIL]" << term::RESET                \
                      << "  " << (msg) << "\n";                                \
            ++g_results.failed;                                                 \
        }                                                                       \
    } while(0)

// ---------------------------------------------------------------------------
// Section banner
// ---------------------------------------------------------------------------
static void section(const char* name)
{
    std::cout << "\n" << term::BOLD << "[ " << name << " ]" << term::RESET << "\n";
}

// ---------------------------------------------------------------------------
// main test body
// ---------------------------------------------------------------------------
static int run(const std::string& imzmlPath)
{
    namespace fs = std::filesystem;

    std::cout << term::BOLD << "\nimzML Parser Test Suite\n" << term::RESET;
    std::cout << std::string(40, '-') << "\n";
    std::cout << "File: " << imzmlPath << "\n";

    // ----------------------------------------------------------------
    // 1. Load
    // ----------------------------------------------------------------
    section("Load");

    imzml::ImzMLFile f;
    try
    {
        f.load(imzmlPath);
        std::cout << term::GREEN << "  [PASS]" << term::RESET
                  << "  File loaded without exception\n";
        ++g_results.passed;
    }
    catch (const std::exception& e)
    {
        std::cout << term::RED << "  [FAIL]" << term::RESET
                  << "  Exception during load: " << e.what() << "\n";
        ++g_results.failed;
        // Cannot continue remaining tests
        goto done;
    }

    // ----------------------------------------------------------------
    // 2. Metadata
    // ----------------------------------------------------------------
    section("Metadata");

    EXPECT_EQ(f.size(), static_cast<std::size_t>(9),
              "3x3 grid => 9 spectra");

    EXPECT_TRUE(f.mode() == imzml::ImagingMode::Continuous,
               "Imaging mode is continuous");

    EXPECT_EQ(f.metadata().scanSettings.maxCountX, 3,
              "maxCountX == 3");

    EXPECT_EQ(f.metadata().scanSettings.maxCountY, 3,
              "maxCountY == 3");

    // ----------------------------------------------------------------
    // 3. Pixel coordinates
    // ----------------------------------------------------------------
    section("Pixel Coordinates");

    // Spectrum 0 => (1,1,1)
    EXPECT_EQ(f.spectrum(0).coord.x, 1, "Spectrum 0 x == 1");
    EXPECT_EQ(f.spectrum(0).coord.y, 1, "Spectrum 0 y == 1");
    EXPECT_EQ(f.spectrum(0).coord.z, 1, "Spectrum 0 z == 1");

    // Spectrum 4 (center of 3x3) => (2,2,1)
    EXPECT_EQ(f.spectrum(4).coord.x, 2, "Spectrum 4 x == 2");
    EXPECT_EQ(f.spectrum(4).coord.y, 2, "Spectrum 4 y == 2");

    // Spectrum 8 (last) => (3,3,1)
    EXPECT_EQ(f.spectrum(8).coord.x, 3, "Spectrum 8 x == 3");
    EXPECT_EQ(f.spectrum(8).coord.y, 3, "Spectrum 8 y == 3");

    // ----------------------------------------------------------------
    // 4. Binary metadata
    // ----------------------------------------------------------------
    section("Binary Metadata");

    // All spectra should have same m/z offset in continuous mode
    {
        bool allSameMzOffset = true;
        const uint64_t firstMzOffset = f.spectrum(0).mzOffset;
        for (std::size_t i = 1; i < f.size(); ++i)
            if (f.spectrum(i).mzOffset != firstMzOffset) { allSameMzOffset = false; break; }
        EXPECT_TRUE(allSameMzOffset, "Continuous mode: all spectra share same m/z offset");
    }

    EXPECT_TRUE(f.spectrum(0).mzDataType == imzml::BinaryDataType::Float32,
                "m/z data type == float32");

    EXPECT_TRUE(f.spectrum(0).intensityDataType == imzml::BinaryDataType::Float32,
                "Intensity data type == float32");

    // Length check: the 3x3 example has 8399 peaks per spectrum
    EXPECT_EQ(f.spectrum(0).mzLength, static_cast<uint64_t>(8399),
              "m/z array length == 8399");

    EXPECT_EQ(f.spectrum(0).intensityLength, static_cast<uint64_t>(8399),
              "Intensity array length == 8399");

    // ----------------------------------------------------------------
    // 5. Validation (binary range check)
    // ----------------------------------------------------------------
    section("Binary Validation");

    {
        auto errors = f.validate();
        EXPECT_TRUE(errors.empty(), "No binary range validation errors");
        if (!errors.empty())
        {
            for (const auto& e : errors)
                std::cout << "    " << e << "\n";
        }
    }

    // ----------------------------------------------------------------
    // 6. Spectrum data read
    // ----------------------------------------------------------------
    section("Spectrum Data");

    {
        auto data = f.getSpectrum(0);

        EXPECT_EQ(data.size(), static_cast<std::size_t>(8399),
                  "Spectrum 0: 8399 peaks");

        // m/z range: should be between 100 and 800 (from pyimzML cross-validation)
        EXPECT_TRUE(data.mz.front() >= 100.0 && data.mz.front() <= 800.0,
                    "m/z[0] in plausible range [100..800]");

        EXPECT_TRUE(data.intensity.front() >= 0.0,
                    "Intensity[0] >= 0");

        // m/z array must be sorted ascending
        bool sorted = true;
        for (std::size_t i = 1; i < data.mz.size(); ++i)
            if (data.mz[i] < data.mz[i-1]) { sorted = false; break; }
        EXPECT_TRUE(sorted, "m/z array is sorted ascending");

        // Cross-validate spectrum 4 (center pixel) intensity sum
        // (pyimzML reference: TIC > 100 for these test files)
        auto center = f.getSpectrum(4);
        double tic = 0.0;
        for (double v : center.intensity) tic += v;
        EXPECT_TRUE(tic > 0.0, "Center spectrum TIC > 0");

        std::cout << term::DIM
                  << "    mz[0]=" << std::fixed << std::setprecision(4)
                  << data.mz[0]
                  << "  mz[last]=" << data.mz.back()
                  << "  intensity[0]=" << data.intensity[0]
                  << "  TIC(center)=" << tic
                  << term::RESET << "\n";
    }

    // ----------------------------------------------------------------
    // 7. Iteration over all spectra
    // ----------------------------------------------------------------
    section("Full Iteration");

    {
        std::size_t totalPeaks = 0;
        bool allOk = true;
        for (std::size_t i = 0; i < f.size(); ++i)
        {
            try
            {
                auto d = f.getSpectrum(i);
                totalPeaks += d.size();
                if (d.mz.size() != d.intensity.size())
                { allOk = false; break; }
            }
            catch (const std::exception& e)
            {
                std::cout << "  Exception spectrum " << i << ": " << e.what() << "\n";
                allOk = false;
                ++g_results.failed;
            }
        }
        EXPECT_TRUE(allOk, "All 9 spectra read without error");
        std::cout << term::DIM
                  << "    Total peaks across all spectra: " << totalPeaks
                  << term::RESET << "\n";
    }

    // ----------------------------------------------------------------
    // 9. Pixel size & UUID
    // ----------------------------------------------------------------
    section("Pixel Size & UUID");

    EXPECT_NEAR(f.metadata().scanSettings.pixelSizeX, 100.0, 0.01,
                "Pixel size X == 100 µm (IMS:1000046)");
    EXPECT_NEAR(f.metadata().scanSettings.pixelSizeY, 100.0, 0.01,
                "Pixel size Y == 100 µm (IMS:1000047)");
    // UUID is the FAKE_UUID literal written by gen_example_data.cpp
    EXPECT_EQ(f.metadata().uuid,
              std::string("12345678-1234-1234-1234-123456789012"),
              "UUID matches IMS:1000080 value in XML");

    // ----------------------------------------------------------------
    // 10. Continuous-mode structural invariants
    // ----------------------------------------------------------------
    section("Continuous Invariants");

    // Shared m/z array starts at byte offset 0
    EXPECT_EQ(f.spectrum(0).mzOffset, static_cast<uint64_t>(0),
              "Shared m/z array starts at IBD byte offset 0");

    // All spectra report the same mzLength
    {
        bool uniform = true;
        for (std::size_t i = 1; i < f.size(); ++i)
            if (f.spectrum(i).mzLength != f.spectrum(0).mzLength)
            { uniform = false; break; }
        EXPECT_TRUE(uniform, "All spectra have identical mzLength in continuous mode");
    }

    // Intensity arrays are stride-spaced: offset[i] == (i+1) * 8399 * sizeof(float32)
    // ibd layout: [mzArray(8399×4)][int0(8399×4)][int1(8399×4)]...
    {
        constexpr uint64_t stride = static_cast<uint64_t>(8399) * 4u;
        bool strideOk = true;
        for (std::size_t i = 0; i < f.size(); ++i)
            if (f.spectrum(i).intensityOffset != (i + 1) * stride)
            { strideOk = false; break; }
        EXPECT_TRUE(strideOk,
                    "Intensity offsets grow by one stride (8399*4 bytes) per spectrum");
    }

    // All pixel (x,y) coordinates are unique across the 3×3 grid
    {
        std::set<std::pair<int,int>> seen;
        bool allUnique = true;
        for (std::size_t i = 0; i < f.size(); ++i)
            if (!seen.insert({f.spectrum(i).coord.x, f.spectrum(i).coord.y}).second)
            { allUnique = false; break; }
        EXPECT_TRUE(allUnique, "All pixel (x,y) coordinates are unique");
    }

    // Spectrum index field is 0-based and monotonically ascending
    {
        bool monoIdx = true;
        for (std::size_t i = 0; i < f.size(); ++i)
            if (f.spectrum(i).index != static_cast<int32_t>(i))
            { monoIdx = false; break; }
        EXPECT_TRUE(monoIdx, "Spectrum indices are 0-based and monotonically ascending");
    }

    // ----------------------------------------------------------------
    // 11. Reference-value cross-validation against gen_example_data.cpp
    //
    // gen_example_data.cpp parameters:
    //   mzStart = 100.0f, mzStep = 700.0f / 8398.0f, N_PEAKS = 8399
    //   center(x,y) = 200 + ((x-1)*NY + (y-1)) * 60  (NY=3)
    //   sigma = 30, amp(x,y) = 0.5 + 0.2*(x+y)
    //   Spectrum order: for y in 1..3, for x in 1..3
    //     i=0: (x=1,y=1) center=200, amp=0.9
    //     i=4: (x=2,y=2) center=440, amp=1.3
    //     i=8: (x=3,y=3) center=680, amp=1.7
    // ----------------------------------------------------------------
    section("Reference Value Cross-Validation");

    // m/z axis endpoints and step
    {
        auto d0 = f.getSpectrum(0);
        const double mzStep = 700.0 / 8398.0;

        EXPECT_NEAR(d0.mz[0],    100.0, 1e-4, "mz[0] == 100.0");
        EXPECT_NEAR(d0.mz[8398], 800.0, 1e-4, "mz[8398] == 800.0");
        EXPECT_NEAR(d0.mz[1] - d0.mz[0], mzStep, 1e-5,
                    "m/z step == 700/8398 Da");

        // Total peaks across all 9 spectra = 9 * 8399 = 75 591
        std::size_t totalPeaksRef = 0;
        for (std::size_t i = 0; i < f.size(); ++i)
            totalPeaksRef += f.getSpectrum(i).size();
        EXPECT_EQ(totalPeaksRef, std::size_t(75591),
                  "Total decoded peaks across grid = 75591");

        // Spectrum 0 intensity[0]: Gaussian tail at mz=100 for center=200, sigma=30, amp=0.9
        const double exp_i0 =
            0.9 * std::exp(-0.5 * std::pow((100.0 - 200.0) / 30.0, 2));
        EXPECT_NEAR(d0.intensity[0], exp_i0, 1e-4,
                    "Spectrum 0 intensity[0] matches Gaussian formula");

        // All intensities of spectrum 0 are non-negative
        bool nonNeg = true;
        for (double v : d0.intensity) if (v < 0.0) { nonNeg = false; break; }
        EXPECT_TRUE(nonNeg, "Spectrum 0: all intensities >= 0");

        // Base peak of spectrum 0 should be near mz=200 with amplitude ≈ 0.9
        auto maxIt0   = std::max_element(d0.intensity.begin(), d0.intensity.end());
        std::size_t idx0 = static_cast<std::size_t>(maxIt0 - d0.intensity.begin());
        EXPECT_NEAR(d0.mz[idx0], 200.0, 2.0,
                    "Spectrum 0 base-peak m/z near 200 Da");
        EXPECT_NEAR(*maxIt0, 0.9, 0.05,
                    "Spectrum 0 peak intensity near 0.9 (amp=0.5+0.2*(1+1))");
    }

    // Spectrum 4: pixel (2,2), center=440, amp=1.3
    {
        auto d4 = f.getSpectrum(4);
        auto maxIt4 = std::max_element(d4.intensity.begin(), d4.intensity.end());
        std::size_t idx4 = static_cast<std::size_t>(maxIt4 - d4.intensity.begin());
        EXPECT_NEAR(d4.mz[idx4], 440.0, 2.0,
                    "Spectrum 4 base-peak m/z near 440 Da");
        EXPECT_NEAR(*maxIt4, 1.3, 0.05,
                    "Spectrum 4 peak intensity near 1.3 (amp=0.5+0.2*(2+2))");
    }

    // Spectrum 8: pixel (3,3), center=680, amp=1.7
    {
        auto d8 = f.getSpectrum(8);
        auto maxIt8 = std::max_element(d8.intensity.begin(), d8.intensity.end());
        std::size_t idx8 = static_cast<std::size_t>(maxIt8 - d8.intensity.begin());
        EXPECT_NEAR(d8.mz[idx8], 680.0, 2.0,
                    "Spectrum 8 base-peak m/z near 680 Da");
        EXPECT_NEAR(*maxIt8, 1.7, 0.05,
                    "Spectrum 8 peak intensity near 1.7 (amp=0.5+0.2*(3+3))");
    }

    // ----------------------------------------------------------------
    // 12. Print file summary
    // ----------------------------------------------------------------
    section("Summary");
    f.printSummary(std::cout);

done:
    // ------------------------------------------------------------------
    // Final result
    // ------------------------------------------------------------------
    std::cout << std::string(40, '-') << "\n";
    std::cout << term::BOLD;
    int total = g_results.passed + g_results.failed;
    std::cout << "Results: " << g_results.passed << "/" << total << " passed";
    if (g_results.failed > 0)
        std::cout << term::RED << "  (" << g_results.failed << " failed)" << term::RESET;
    std::cout << term::RESET << "\n\n";

    return g_results.failed == 0 ? 0 : 1;
}

// ---------------------------------------------------------------------------
// runWriterTest – continuous round-trip: write then read back and compare
// ---------------------------------------------------------------------------
static int runWriterTest(const std::string& /*originalPath*/)
{
    namespace fs = std::filesystem;

    g_results = {};  // reset
    std::cout << term::BOLD << "\nimzML Writer Round-Trip Test (continuous)\n" << term::RESET;
    std::cout << std::string(46, '-') << "\n";

    // ---- Build synthetic data ----------------------------------------
    const int NX = 2, NY = 3;
    const std::size_t N_PEAKS = 5;

    // Fixed shared m/z
    std::vector<double> mz = {100.0, 200.0, 300.0, 400.0, 500.0};

    struct Pixel { imzml::Coordinate coord; std::vector<double> intensity; };
    std::vector<Pixel> pixels;
    for (int y = 1; y <= NY; ++y)
        for (int x = 1; x <= NX; ++x)
        {
            std::vector<double> iv(N_PEAKS);
            for (std::size_t k = 0; k < N_PEAKS; ++k)
                iv[k] = static_cast<double>((x * 10 + y) * (k + 1));
            pixels.push_back({{x, y, 1}, iv});
        }

    // ---- Write ----------------------------------------------------------
    section("Write (continuous)");

    const std::string outDir     = "/tmp/test_imzml_writer";
    const std::string outImzML   = outDir + "/RoundTrip_Continuous.imzML";
    fs::create_directories(outDir);

    try
    {
        imzml::ImzMLWriter w;
        imzml::ImzMLWriter::Options opts;
        opts.mode       = imzml::ImagingMode::Continuous;
        opts.mzType     = imzml::BinaryDataType::Float32;
        opts.intType    = imzml::BinaryDataType::Float32;
        opts.pixelSizeX = 100.0;
        opts.pixelSizeY = 100.0;
        opts.instrumentName = "Test Writer";
        w.open(outImzML, opts);

        for (const auto& p : pixels)
            w.addSpectrum(p.coord, mz, p.intensity);

        w.close();
        std::cout << term::GREEN << "  [PASS]" << term::RESET
                  << "  Writer closed without exception\n";
        ++g_results.passed;
    }
    catch (const std::exception& e)
    {
        std::cout << term::RED << "  [FAIL]" << term::RESET
                  << "  Writer threw: " << e.what() << "\n";
        ++g_results.failed;
        goto writer_done;
    }

    EXPECT_TRUE(fs::exists(outImzML),                      "Output .imzML file exists");
    EXPECT_TRUE(fs::exists(outDir + "/RoundTrip_Continuous.ibd"), "Output .ibd file exists");

    // ---- Read back ------------------------------------------------------
    section("Read-back (continuous)");

    {
        imzml::ImzMLFile f2;
        try
        {
            f2.load(outImzML);
            std::cout << term::GREEN << "  [PASS]" << term::RESET
                      << "  Written file loaded without exception\n";
            ++g_results.passed;
        }
        catch (const std::exception& e)
        {
            std::cout << term::RED << "  [FAIL]" << term::RESET
                      << "  Load of written file failed: " << e.what() << "\n";
            ++g_results.failed;
            goto writer_done;
        }

        EXPECT_EQ(f2.size(), pixels.size(), "Spectra count matches");
        EXPECT_TRUE(f2.mode() == imzml::ImagingMode::Continuous, "Mode == continuous");
        EXPECT_EQ(f2.metadata().scanSettings.maxCountX, NX, "maxCountX == 2");
        EXPECT_EQ(f2.metadata().scanSettings.maxCountY, NY, "maxCountY == 3");

        // Validate all binary ranges
        auto errs = f2.validate();
        EXPECT_TRUE(errs.empty(), "No binary range validation errors");

        // Check per-spectrum data
        bool allMatch = true;
        for (std::size_t i = 0; i < pixels.size(); ++i)
        {
            auto d = f2.getSpectrum(i);
            if (d.mz.size() != N_PEAKS || d.intensity.size() != N_PEAKS)
            {
                allMatch = false; break;
            }
            for (std::size_t k = 0; k < N_PEAKS; ++k)
            {
                if (std::abs(d.mz[k] - mz[k]) > 1e-3)        { allMatch = false; break; }
                if (std::abs(d.intensity[k] - pixels[i].intensity[k]) > 1e-2)
                                                                { allMatch = false; break; }
            }
            if (!allMatch) break;
        }
        EXPECT_TRUE(allMatch, "All written values round-trip correctly");

        // Coordinates
        EXPECT_EQ(f2.spectrum(0).coord.x, pixels[0].coord.x, "Spectrum 0 coord.x round-trips");
        EXPECT_EQ(f2.spectrum(0).coord.y, pixels[0].coord.y, "Spectrum 0 coord.y round-trips");

        // Pixel size
        EXPECT_NEAR(f2.metadata().scanSettings.pixelSizeX, 100.0, 0.5, "pixelSizeX round-trips");
    }

writer_done:
    std::cout << std::string(46, '-') << "\n";
    std::cout << term::BOLD;
    int total = g_results.passed + g_results.failed;
    std::cout << "Results: " << g_results.passed << "/" << total << " passed";
    if (g_results.failed > 0)
        std::cout << term::RED << "  (" << g_results.failed << " failed)" << term::RESET;
    std::cout << term::RESET << "\n\n";
    return g_results.failed == 0 ? 0 : 1;
}

// ---------------------------------------------------------------------------
// runProcessedTest – write processed-mode file, read back, compare
// ---------------------------------------------------------------------------
static int runProcessedTest(const std::string& /*originalPath*/)
{
    namespace fs = std::filesystem;

    g_results = {};  // reset
    std::cout << term::BOLD << "\nimzML Writer Round-Trip Test (processed)\n" << term::RESET;
    std::cout << std::string(44, '-') << "\n";

    const int NX = 2, NY = 2;

    // Each pixel has a different m/z axis (hallmark of processed mode)
    struct Pixel {
        imzml::Coordinate   coord;
        std::vector<double> mz;
        std::vector<double> intensity;
    };
    std::vector<Pixel> pixels;
    for (int y = 1; y <= NY; ++y)
        for (int x = 1; x <= NX; ++x)
        {
            std::size_t nPeaks = static_cast<std::size_t>(2 + x + y);  // varying lengths
            std::vector<double> mzv(nPeaks), iv(nPeaks);
            for (std::size_t k = 0; k < nPeaks; ++k)
            {
                mzv[k] = 100.0 * (k + 1) + x * 5.0;
                iv[k]  = static_cast<double>((x + y) * (k + 1) * 3);
            }
            pixels.push_back({{x, y, 1}, mzv, iv});
        }

    // ---- Write ----------------------------------------------------------
    section("Write (processed)");

    const std::string outDir   = "/tmp/test_imzml_processed";
    const std::string outImzML = outDir + "/RoundTrip_Processed.imzML";
    fs::create_directories(outDir);

    try
    {
        imzml::ImzMLWriter w;
        imzml::ImzMLWriter::Options opts;
        opts.mode    = imzml::ImagingMode::Processed;
        opts.mzType  = imzml::BinaryDataType::Float64;
        opts.intType = imzml::BinaryDataType::Float32;
        w.open(outImzML, opts);

        for (const auto& p : pixels)
            w.addSpectrum(p.coord, p.mz, p.intensity);

        w.close();
        std::cout << term::GREEN << "  [PASS]" << term::RESET
                  << "  Processed writer closed without exception\n";
        ++g_results.passed;
    }
    catch (const std::exception& e)
    {
        std::cout << term::RED << "  [FAIL]" << term::RESET
                  << "  Processed writer threw: " << e.what() << "\n";
        ++g_results.failed;
        goto processed_done;
    }

    EXPECT_TRUE(fs::exists(outImzML),                       "Output .imzML file exists");
    EXPECT_TRUE(fs::exists(outDir + "/RoundTrip_Processed.ibd"), "Output .ibd file exists");

    // ---- Read back ------------------------------------------------------
    section("Read-back (processed)");

    {
        imzml::ImzMLFile f3;
        try
        {
            f3.load(outImzML);
            std::cout << term::GREEN << "  [PASS]" << term::RESET
                      << "  Written processed file loaded without exception\n";
            ++g_results.passed;
        }
        catch (const std::exception& e)
        {
            std::cout << term::RED << "  [FAIL]" << term::RESET
                      << "  Load of written processed file failed: " << e.what() << "\n";
            ++g_results.failed;
            goto processed_done;
        }

        EXPECT_EQ(f3.size(), pixels.size(), "Spectra count matches");
        EXPECT_TRUE(f3.mode() == imzml::ImagingMode::Processed, "Mode == processed");

        auto errs = f3.validate();
        EXPECT_TRUE(errs.empty(), "No binary range validation errors");

        // Each spectrum should have its own m/z array (different offsets)
        bool differentMzOffsets = false;
        for (std::size_t i = 1; i < f3.size(); ++i)
            if (f3.spectrum(i).mzOffset != f3.spectrum(0).mzOffset)
            { differentMzOffsets = true; break; }
        EXPECT_TRUE(differentMzOffsets, "Processed mode: spectra have different m/z offsets");

        // Validate varying lengths
        bool lengthsVary = false;
        const uint64_t first = f3.spectrum(0).mzLength;
        for (std::size_t i = 1; i < f3.size(); ++i)
            if (f3.spectrum(i).mzLength != first) { lengthsVary = true; break; }
        EXPECT_TRUE(lengthsVary, "Processed mode: spectra have varying m/z lengths");

        // Verify data round-trip
        bool allMatch = true;
        for (std::size_t i = 0; i < pixels.size(); ++i)
        {
            auto d     = f3.getSpectrum(i);
            auto& refP = pixels[i];
            if (d.mz.size() != refP.mz.size()) { allMatch = false; break; }
            for (std::size_t k = 0; k < d.mz.size(); ++k)
            {
                if (std::abs(d.mz[k]        - refP.mz[k])        > 1e-4) { allMatch = false; break; }
                if (std::abs(d.intensity[k] - refP.intensity[k]) > 1e-2) { allMatch = false; break; }
            }
            if (!allMatch) break;
        }
        EXPECT_TRUE(allMatch, "All processed-mode values round-trip correctly");
    }

processed_done:
    std::cout << std::string(44, '-') << "\n";
    std::cout << term::BOLD;
    int total = g_results.passed + g_results.failed;
    std::cout << "Results: " << g_results.passed << "/" << total << " passed";
    if (g_results.failed > 0)
        std::cout << term::RED << "  (" << g_results.failed << " failed)" << term::RESET;
    std::cout << term::RESET << "\n\n";
    return g_results.failed == 0 ? 0 : 1;
}

// ---------------------------------------------------------------------------
// runErrorCaseTests – verifies that all documented error paths throw correctly
// ---------------------------------------------------------------------------
static int runErrorCaseTests(const std::string& imzmlPath)
{
    namespace fs = std::filesystem;

    g_results = {};
    std::cout << term::BOLD << "\nError-Case Tests\n" << term::RESET;
    std::cout << std::string(40, '-') << "\n";

    // ---- 1. Load nonexistent file ------------------------------------
    section("Error: Nonexistent imzML");
    {
        imzml::ImzMLFile bad;
        bool threw = false;
        try { bad.load("/nonexistent/path/does_not_exist.imzML"); }
        catch (const std::exception&) { threw = true; }
        EXPECT_TRUE(threw, "load() of nonexistent file throws");
    }

    // ---- 2. spectrum() index out of bounds --------------------------
    section("Error: spectrum() Out of Bounds");
    {
        imzml::ImzMLFile f;
        f.load(imzmlPath);
        bool threw = false;
        try { (void)f.spectrum(9999); }
        catch (const std::exception&) { threw = true; }
        EXPECT_TRUE(threw, "spectrum(9999) throws std::out_of_range");
    }

    // ---- 3. getSpectrum() index out of bounds -----------------------
    section("Error: getSpectrum() Out of Bounds");
    {
        imzml::ImzMLFile f;
        f.load(imzmlPath);
        bool threw = false;
        try { (void)f.getSpectrum(9999); }
        catch (const std::exception&) { threw = true; }
        EXPECT_TRUE(threw, "getSpectrum(9999) throws");
    }

    // ---- 4. Writer: addSpectrum before open -------------------------
    section("Error: Writer Not Opened");
    {
        imzml::ImzMLWriter w;
        bool threw = false;
        try { w.addSpectrum({1, 1, 1}, {100.0}, {1.0}); }
        catch (const std::exception&) { threw = true; }
        EXPECT_TRUE(threw, "addSpectrum on un-opened writer throws");
    }

    // ---- 5. Writer: double-open -------------------------------------
    section("Error: Writer Double-Open");
    {
        const std::string tmpDir = "/tmp/test_imzml_errcase";
        fs::create_directories(tmpDir);
        imzml::ImzMLWriter w;
        w.open(tmpDir + "/ec_first.imzML", {});
        bool threw = false;
        try { w.open(tmpDir + "/ec_second.imzML", {}); }
        catch (const std::exception&) { threw = true; }
        EXPECT_TRUE(threw, "Calling open() on already-open writer throws");
        try { w.close(); } catch (...) {}  // cleanup
    }

    // ---- 6. Continuous mode: mismatched m/z length ------------------
    section("Error: Continuous Mismatched m/z Length");
    {
        const std::string tmpDir = "/tmp/test_imzml_errcase";
        fs::create_directories(tmpDir);
        bool threw = false;
        {
            imzml::ImzMLWriter w;
            imzml::ImzMLWriter::Options opts;
            opts.mode = imzml::ImagingMode::Continuous;
            w.open(tmpDir + "/ec_mismatch.imzML", opts);
            // First call: establishes shared mzLength = 2
            w.addSpectrum({1, 1, 1}, {100.0, 200.0}, {1.0, 2.0});
            try
            {
                // Second call: length 3 != established 2 → throws
                w.addSpectrum({2, 1, 1}, {100.0, 200.0, 300.0}, {1.0, 2.0, 3.0});
            }
            catch (const std::exception&) { threw = true; }
            // Destructor silently close()es the writer (already tested doesn't crash)
        }
        EXPECT_TRUE(threw, "Continuous mode: mismatched m/z lengths throws");
    }

    std::cout << std::string(40, '-') << "\n";
    std::cout << term::BOLD;
    int total2 = g_results.passed + g_results.failed;
    std::cout << "Results: " << g_results.passed << "/" << total2 << " passed";
    if (g_results.failed > 0)
        std::cout << term::RED << "  (" << g_results.failed << " failed)" << term::RESET;
    std::cout << term::RESET << "\n\n";
    return g_results.failed == 0 ? 0 : 1;
}

// ---------------------------------------------------------------------------
// runInt32WriterTest – round-trip test for Float64 m/z + Int32 intensities
// (type combination not exercised by the other writer tests)
// ---------------------------------------------------------------------------
static int runInt32WriterTest()
{
    namespace fs = std::filesystem;

    g_results = {};
    std::cout << term::BOLD
              << "\nimzML Writer Round-Trip Test (Float64 mz + Int32 intensity)\n"
              << term::RESET;
    std::cout << std::string(56, '-') << "\n";

    const std::string outDir   = "/tmp/test_imzml_int32";
    const std::string outImzML = outDir + "/RoundTrip_Int32.imzML";
    fs::create_directories(outDir);

    // Integer intensities so Int32 truncation is lossless
    const std::vector<double> sharedMz = {100.0, 200.0, 300.0, 400.0};
    const std::vector<std::vector<double>> ints = {
        { 10.0,  20.0,  30.0,  40.0},
        { 50.0,  60.0,  70.0,  80.0},
        { 90.0, 100.0, 110.0, 120.0},
        {130.0, 140.0, 150.0, 160.0},
    };

    // ---- Write (Float64 mz, Int32 intensity, continuous) ------------
    section("Write (Float64 mz + Int32 intensity)");

    try
    {
        imzml::ImzMLWriter w;
        imzml::ImzMLWriter::Options opts;
        opts.mode    = imzml::ImagingMode::Continuous;
        opts.mzType  = imzml::BinaryDataType::Float64;
        opts.intType = imzml::BinaryDataType::Int32;
        w.open(outImzML, opts);

        for (std::size_t i = 0; i < 4; ++i)
            w.addSpectrum(
                {static_cast<int32_t>(i % 2 + 1),
                 static_cast<int32_t>(i / 2 + 1), 1},
                sharedMz, ints[i]);

        EXPECT_EQ(w.spectraWritten(), std::size_t(4),
                  "spectraWritten() == 4 before close()");
        w.close();

        std::cout << term::GREEN << "  [PASS]" << term::RESET
                  << "  Writer closed without exception\n";
        ++g_results.passed;
    }
    catch (const std::exception& e)
    {
        std::cout << term::RED << "  [FAIL]" << term::RESET
                  << "  Writer threw: " << e.what() << "\n";
        ++g_results.failed;
        goto int32_done;
    }

    EXPECT_TRUE(fs::exists(outImzML),                  "Output .imzML file exists");
    EXPECT_TRUE(fs::exists(outDir + "/RoundTrip_Int32.ibd"), "Output .ibd file exists");

    // ---- Read back --------------------------------------------------
    section("Read-back (Float64 mz + Int32 intensity)");

    {
        imzml::ImzMLFile f4;
        try
        {
            f4.load(outImzML);
            std::cout << term::GREEN << "  [PASS]" << term::RESET
                      << "  File loaded without exception\n";
            ++g_results.passed;
        }
        catch (const std::exception& e)
        {
            std::cout << term::RED << "  [FAIL]" << term::RESET
                      << "  Load failed: " << e.what() << "\n";
            ++g_results.failed;
            goto int32_done;
        }

        EXPECT_EQ(f4.size(), std::size_t(4), "4 spectra");
        EXPECT_TRUE(f4.mode() == imzml::ImagingMode::Continuous,
                    "Mode == continuous");
        EXPECT_TRUE(f4.spectrum(0).mzDataType == imzml::BinaryDataType::Float64,
                    "m/z data type == Float64");
        EXPECT_TRUE(f4.spectrum(0).intensityDataType == imzml::BinaryDataType::Int32,
                    "Intensity data type == Int32");

        auto errs = f4.validate();
        EXPECT_TRUE(errs.empty(), "No binary range validation errors");

        // Continuous: all spectra share the same m/z offset
        {
            bool allSame = true;
            for (std::size_t i = 1; i < f4.size(); ++i)
                if (f4.spectrum(i).mzOffset != f4.spectrum(0).mzOffset)
                { allSame = false; break; }
            EXPECT_TRUE(allSame, "All m/z offsets identical (continuous Float64)");
        }

        // Float64 m/z round-trips exactly for representable values
        {
            auto d0 = f4.getSpectrum(0);
            EXPECT_EQ(d0.mz.size(), std::size_t(4), "m/z array size == 4");
            bool mzExact = true;
            for (std::size_t k = 0; k < sharedMz.size(); ++k)
                if (d0.mz[k] != sharedMz[k]) { mzExact = false; break; }
            EXPECT_TRUE(mzExact, "Float64 m/z values round-trip without precision loss");
        }

        // Int32 intensity values round-trip exactly for whole-number inputs
        {
            bool allMatch = true;
            for (std::size_t i = 0; i < 4 && allMatch; ++i)
            {
                auto d = f4.getSpectrum(i);
                if (d.intensity.size() != ints[i].size()) { allMatch = false; break; }
                for (std::size_t k = 0; k < ints[i].size() && allMatch; ++k)
                    if (std::abs(d.intensity[k] - ints[i][k]) > 0.5)
                        allMatch = false;
            }
            EXPECT_TRUE(allMatch,
                        "Int32 intensity values round-trip without loss");
        }
    }

int32_done:
    std::cout << std::string(56, '-') << "\n";
    std::cout << term::BOLD;
    int total3 = g_results.passed + g_results.failed;
    std::cout << "Results: " << g_results.passed << "/" << total3 << " passed";
    if (g_results.failed > 0)
        std::cout << term::RED << "  (" << g_results.failed << " failed)" << term::RESET;
    std::cout << term::RESET << "\n\n";
    return g_results.failed == 0 ? 0 : 1;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char* argv[])
{
    namespace fs = std::filesystem;

    bool writerTest    = false;
    bool processedTest = false;
    bool errorTest     = false;
    bool int32Test     = false;
    std::string imzmlPath;

    for (int i = 1; i < argc; ++i)
    {
        std::string arg(argv[i]);
        if      (arg == "--writer-test")    { writerTest    = true; }
        else if (arg == "--processed-test") { processedTest = true; }
        else if (arg == "--error-test")     { errorTest     = true; }
        else if (arg == "--int32-test")     { int32Test     = true; }
        else                               { imzmlPath = arg; }
    }

    if (imzmlPath.empty())
    {
        fs::path exe(argv[0]);
        imzmlPath = (exe.parent_path() / "data" / "Example_Continuous.imzML").string();
        if (!fs::exists(imzmlPath))
            imzmlPath = "data/Example_Continuous.imzML";
    }

    // Single-suite flags (kept for CI isolation)
    if (writerTest)    return runWriterTest(imzmlPath);
    if (processedTest) return runProcessedTest(imzmlPath);
    if (errorTest)     return runErrorCaseTests(imzmlPath);
    if (int32Test)     return runInt32WriterTest();

    // Default: run all suites; return non-zero if any fails
    if (!fs::exists(imzmlPath))
    {
        std::cerr << "Test data not found: " << imzmlPath << "\n"
                  << "Generate it first:\n"
                  << "  ./gen_example_data data/\n"
                  << "Or pass the path directly:\n"
                  << "  ./test_imzml /path/to/Example_Continuous.imzML\n";
        return 2;
    }

    int rc = 0;
    rc |= run(imzmlPath);
    rc |= runWriterTest(imzmlPath);
    rc |= runProcessedTest(imzmlPath);
    rc |= runErrorCaseTests(imzmlPath);
    rc |= runInt32WriterTest();
    return rc;
}
